SELECT TOP (1000) [sensorId]
      ,[count]
      ,[temperatureMin]
      ,[windMin]
      ,[humidityMin]
      ,[co2Min]
      ,[temperatureMax]
      ,[windMax]
      ,[humidityMax]
      ,[co2Max]
      ,[temperatureAvg]
      ,[windAvg]
      ,[humidityAvg]
      ,[co2Avg]
  FROM [dbo].[sensorStats]